"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AdminGate } from "@/components/AdminGate";
import { Devotion, devotionImageUrl } from "@/lib/devotions";
import { requireSupabase } from "@/lib/supabase";
type DirectoryDevotion = Devotion & { linkedCount: number };
export default function DevotionsPage() {
  const db = useMemo(() => requireSupabase(), []); const [rows, setRows] = useState<DirectoryDevotion[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; void (async () => { const [devotionsResult, itemsResult] = await Promise.all([db.from("devotions").select("id,slug,language_code,title,short_description,description,cover_image_path,status,sort_order").order("sort_order"), db.from("devotion_items").select("devotion_id")]); if (!active) return; const failure = devotionsResult.error || itemsResult.error; if (failure) setError(failure.message); else { const counts = new Map<string, number>(); for (const item of itemsResult.data ?? []) counts.set(item.devotion_id, (counts.get(item.devotion_id) ?? 0) + 1); setRows(((devotionsResult.data ?? []) as Devotion[]).map(row => ({ ...row, linkedCount: counts.get(row.id) ?? 0 }))); } setLoading(false); })(); return () => { active = false; }; }, [db]);
  const visible = rows.filter(row => `${row.title} ${row.short_description}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminGate><main className="page devotion-directory"><div className="page-head"><div><p className="eyebrow">Editorial workspace</p><h1 className="title">Devotions</h1><p className="description">Create permanent devotional collections independently from Today.</p></div><Link className="button" href="/devotions/new">+ Create devotion</Link></div><div className="devotion-directory-toolbar"><input className="input" aria-label="Search devotions" placeholder="Search devotions" value={query} onChange={event => setQuery(event.target.value)} /><span>{visible.length} devotion{visible.length === 1 ? "" : "s"}</span></div>{error && <p className="alert error">{error}</p>}{loading ? <p className="status-line">Loading devotions…</p> : <div className="devotion-grid">{visible.map(devotion => { const cover = devotionImageUrl(devotion.cover_image_path); return <article className="devotion-directory-card" key={devotion.id}><div className="devotion-directory-cover">{cover ? <img src={cover} alt="" /> : <span aria-hidden="true">✦</span>}<span className={`badge ${devotion.status}`}>{devotion.status === "ready" ? "Published" : devotion.status}</span></div><div className="devotion-directory-body"><div><h2>{devotion.title}</h2><p>{devotion.short_description || "No short description yet."}</p></div><div className="devotion-card-footer"><span>{devotion.linkedCount} devotional item{devotion.linkedCount === 1 ? "" : "s"}</span><Link className="button secondary" href={`/devotions/${devotion.id}`}>Edit devotion</Link></div></div></article>; })}</div>}{!loading && visible.length === 0 && <div className="card devotion-empty"><h2 className="card-title">No devotions found</h2><p>Try another search, or create a new devotional collection.</p></div>}</main></AdminGate>;
}
