"use client";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { devotionImageUrl } from "@/lib/devotions";
import { adminAuthorizationHeader, requireSupabase } from "@/lib/supabase";
type MediaAsset = { id: string; storage_path: string; public_url: string | null; alt_text: string | null };
export function DevotionCoverManager({ devotionId, value, onChange }: { devotionId: string; value: string | null; onChange: (value: string) => void }) {
  const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [localPreview, setLocalPreview] = useState(""); const [assets, setAssets] = useState<MediaAsset[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { let active = true; void requireSupabase().from("content_media").select("id,storage_path,public_url,alt_text").eq("media_type", "image").order("created_at", { ascending: false }).limit(18).then(({ data }) => { if (active) setAssets((data ?? []) as MediaAsset[]); }); return () => { active = false; }; }, []);
  useEffect(() => () => { if (localPreview) URL.revokeObjectURL(localPreview); }, [localPreview]);
  function chooseFile(event: ChangeEvent<HTMLInputElement>) { const next = event.target.files?.[0]; setMessage(""); if (!next) return; if (!["image/jpeg", "image/png", "image/webp"].includes(next.type) || next.size > 5 * 1024 * 1024) { setMessage("Choose a JPEG, PNG or WebP image smaller than 5 MB."); return; } if (localPreview) URL.revokeObjectURL(localPreview); setFile(next); setLocalPreview(URL.createObjectURL(next)); }
  async function upload() { if (!file || devotionId === "new") return; setBusy(true); setMessage(""); try { const body = new FormData(); body.set("file", file); body.set("devotionId", devotionId); const response = await fetch("/api/admin/devotions/cover", { method: "POST", headers: await adminAuthorizationHeader(), body }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Upload failed."); onChange(payload.storagePath); setFile(null); setLocalPreview(""); setMessage("Cover uploaded and assigned."); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload failed."); } finally { setBusy(false); } }
  async function removeUpload() { if (devotionId === "new") return; setBusy(true); setMessage(""); try { const response = await fetch("/api/admin/devotions/cover", { method: "DELETE", headers: { ...(await adminAuthorizationHeader()), "Content-Type": "application/json" }, body: JSON.stringify({ devotionId }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Cover removal failed."); onChange(""); setMessage(payload.warning || "Uploaded cover removed."); } catch (error) { setMessage(error instanceof Error ? error.message : "Cover removal failed."); } finally { setBusy(false); } }
  const preview = localPreview || devotionImageUrl(value);
  const ownsUpload = Boolean(value?.startsWith(`devotions/${devotionId}/`));
  return <div className="devotion-cover-manager"><div className="devotion-cover-preview">{preview ? <img src={preview} alt="Devotion cover preview" /> : <span>No cover assigned</span>}</div><div className="devotion-cover-actions"><input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile} /><button className="button secondary" type="button" onClick={() => input.current?.click()}>{file ? "Choose another image" : "Upload new image"}</button><button className="button" type="button" disabled={!file || busy || devotionId === "new"} onClick={() => void upload()}>{busy ? "Uploading…" : "Upload & use cover"}</button>{ownsUpload && <button className="button secondary" type="button" disabled={busy} onClick={() => void removeUpload()}>Remove uploaded cover</button>}{devotionId === "new" && <small>Save the devotion before uploading a cover.</small>}</div>{message && <p className="devotion-inline-message">{message}</p>}<div><h3 className="card-title">Choose from existing media</h3><p className="description">Reuse an image already uploaded through Studio.</p><div className="devotion-media-grid">{assets.map(asset => { const url = asset.public_url || devotionImageUrl(asset.storage_path); return <button type="button" className={value === (asset.public_url || asset.storage_path) ? "selected" : ""} key={asset.id} onClick={() => onChange(asset.public_url || asset.storage_path)}><img src={url} alt={asset.alt_text || "Existing media"} /></button>; })}</div></div><details><summary>Use an existing CDN path or image URL</summary><input className="input mt-3" value={value ?? ""} placeholder="devotions/… or https://…" onChange={event => onChange(event.target.value)} /></details></div>;
}
